#!/bin/bash
# 
# script.sh
# 
# Description
# 
# Name
# Month. Year

if [ "$(id -u)" != "0" ]; then
    printf "${error}ERROR: The script must be run with sudo privileges!${reset}\n"
    exit 1
fi

printf "${info}Starting <fill in> script${reset}\n"



exit 0
