version: '3'

name: webmail-state

services:
  mail:
    container_name: webmail
    build: .
    ports:
      - "110:110/tcp"
      - "25:25/tcp"
    volumes:
      - ./startup:/startup:ro
    environment:
      - DOMAIN_NAME=frog.com
      - SUB_DOMAIN=mail
