version: '3'

name: bind9-state

services:
  bind9:
    build:
      context: .
      dockerfile: Dockerfile
    image: bind9_image
    container_name: bind9
    environment:
      - TZ=America/New_York
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./config:/etc/bind
      - ./cache:/var/cache/bind
      - ./records:/var/lib/bind
      - ./logs:/var/log/bind9
    restart: unless-stopped
