#!/bin/bash
#
# Install vim, tmux and configure
# Create tmux session, call hardening script, and attach

if [ $(id -u) != 0 ]; then
    echo "You must use sudo to run this script!"
    exit 1
fi

# move to home directory and copy personal scripts there
cd ~
cp ~/CCDC/personal-scripts/lmiller/* .

# install useful utilities
yum install -y vim
yum install -y tmux

mv tmux-lm.conf .tmux.conf
mv vim-lm.conf .vimrc

# Setup tmux session
SESSIONNAME='ccdc-lm'
WINDOWNAME='harden'
tmux has-session -t $SESSIONNAME &> /dev/null

if [ $? != 0 ]
then
        tmux new-session -d -s $SESSIONNAME -n $WINDOWNAME
        sleep 1

        tmux split-window -h -t $SESSIONNAME:0
        tmux split-window -v -t 0
        tmux split-window -v -t 2

        tmux send-keys -t 0 "cd ~; clear" Enter
        tmux send-keys -t 1 "cd ~; clear" Enter
        tmux send-keys -t 2 "cd /var/www; clear" Enter
        tmux send-keys -t 3 "cd /var/www; clear" Enter


        tmux new-window -n scripts
        sleep 1
        tmux send-keys -t 0 "./sonicjazz" Enter
fi

tmux source ./tmux-lm.conf

tmux a -t $SESSIONNAME
