#!/bin/bash
#
# Install vim, tmux and configure
# Create tmux session, call hardening script, and attach

# Make sure script is run as root
if [ $(id -u) != 0 ]; then
    echo "You must use sudo to run this script!"
    exit 1
fi

# Set working directory to the user's home directory
export WK_DIR=$(getent passwd $SUDO_USER | cut -d: -f6)

# Set and export DISTRO_ID for compatibility with other scripts
. /etc/os-release
export DISTRO_ID=$ID

# Set and export DISTRO for compatibility with other scripts
export DISTRO="redhat"

# Set and export PKG_MAN for compatibility with other scripts
export PKG_MAN="yum"

# move to working directory and copy personal scripts there
cd $WK_DIR

if [! -d CCDC ]; then
    git clone https://github.com/CedarvilleCyber/CCDC
fi

cp CCDC/personal-scripts/lmiller/* .

# install useful utilities
yum install -y vim
yum install -y tmux

cp tmux-lm.conf .tmux.conf
chown $SUDO_USER .tmux.conf
chmod 644 .tmux.conf
cp vim-lm.conf .vimrc
chown $SUDO_USER .vimrc
chmod 644 .vimrc

# Setup tmux session
SESSIONNAME='ccdc-lm'
WINDOWNAME='harden'
tmux has-session -t $SESSIONNAME &> /dev/null

if [ $? != 0 ]; then
    tmux new-session -d -s $SESSIONNAME -n $WINDOWNAME
    sleep 1

    tmux split-window -h -t $SESSIONNAME:0
    tmux split-window -v -t 0
    tmux split-window -v -t 1

    tmux send-keys -t 0 "cd $WK_DIR; clear" Enter
    tmux send-keys -t 1 "cd $WK_DIR; clear" Enter
    tmux send-keys -t 2 "cd /var/www; clear" Enter
    tmux send-keys -t 3 "cd /var/www; clear" Enter


    tmux new-window -n scripts
    sleep 1
    tmux send-keys -t 0 "./sonicjazz" Enter
fi

tmux source ./tmux-lm.conf

tmux a -t $SESSIONNAME
