#!/bin/bash

SESSIONNAME='ccdc-lm'
tmux has-session -t $SESSIONNAME &> /dev/null

if [ $? != 0 ]; then
    echo "Create tmux session by running blitz!"
    exit 1;
fi

tmux source ./tmux-lm.conf

tmux a -t $SESSIONNAME
