@echo off
::Splunk Universal Forwarder Setup for Windows Hosts

msiexec.exe /i splunkuniversalforwarder_x86.msi RECEIVING_INDEXER="172.20.241.20:9997" WINEVENTLOG_FWD_ENABLE=1 WINEVENTLOG_SET_ENABLE=1 WINEVENTLOG_SEC_ENABLE=1 WINEVENTLOG_SYS_ENABLE=1 WINEVENTLOG_APPS_ENABLE=1 AGREETOLICENSE=Yes /quiet
