# docker compose -f ecomm-state.yml --env-file ccdc.env up --remove-orphans
#
# walk through prestashop install (changes persist in volume)
#   store name: Bob's Duck Shop
#   name: Bob Ducky
#   prestashop account: bob@allsafe.com|PRESTA_SITE_PASSWD
#   database server: mysql
#   database name: prestashop
#   database creds: prestashop|PRESTA_DB_PASSWD
#
# docker exec -it prestashop bash (changes persist in volume)
#   rm -rf install
#   mv admin ADMIN_PANEL
#
# add curl_exec to php.ini disable_functions, add read_only limitations to volumes, and run docker restart prestashop
#
# docker exec -it presta_db bash (changes DON'T persist in volume) ??
#   mysql_secure_installation
# 
# backup all volumes and configs, integrity check these periodically
# 

# what about an earlier version of prestashop??

name: ecomm-state

services:
  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:latest
    environment:
      DB_SERVER: mysql
      DB_NAME: prestashop
      DB_USER: prestashop
      DB_PASSWD: ${PRESTA_DB_PASSWD}
    restart: unless-stopped
    ports:
      - '${PRESTA_PORT}:80'
    networks:
      - presta_net
    volumes:
      - web_data:/var/www/html
      - ./setup-ecomm.sh:/root/setup-ecomm.sh:ro
    configs:
      - source: secure-apache-conf
        target: /etc/apache2/apache2.conf
      - source: secure-php-conf
        target: /usr/local/etc/php/php.ini
    depends_on:
      - mysql
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    restart: unless-stopped
    ports:
      - '${PHPMYADMIN_PORT}:80'
    networks:
      - pma_net
    depends_on:
      - mysql
  
  mysql:
    container_name: presta_db
    image: mysql:latest
    environment:
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: ${PRESTA_DB_PASSWD}
      MYSQL_ROOT_PASSWORD: ${ROOT_DB_PASSWD}
    restart: unless-stopped
    networks:
      - presta_net
      - pma_net
    volumes:
      - db_data:/var/lib/mysql

networks:
  presta_net:
  pma_net:

volumes:
  db_data:
  web_data:

configs:
  secure-apache-conf:
    file: ./apache2.conf
  secure-php-conf:
    file: ./php.ini
