useradd -m -s /bin/bash administrator && echo changeme | passwd administrator --stdin
useradd -m -s /bin/bash kbdavila && echo letmein | passwd kbdavila --stdin
useradd -m -s /bin/bash cthumphrey && echo baseball | passwd cthumphrey --stdin
useradd -m -s /bin/bash abnederveld && echo master | passwd abnederveld --stdin
useradd -m -s /bin/bash grporter && echo shadow | passwd grporter --stdin
useradd -m -s /bin/bash stbenoit && echo monkey | passwd stbenoit --stdin
useradd -m -s /bin/bash mkweirich && echo abc123 | passwd mkweirich --stdin
useradd -m -s /bin/bash rjcavallaro && echo 6969 | passwd rjcavallaro --stdin
useradd -m -s /bin/bash ccmelton && echo jordan | passwd ccmelton --stdin
useradd -m -s /bin/bash laschoppe && echo ranger | passwd laschoppe --stdin
useradd -m -s /bin/bash cthagen && echo iwantu | passwd cthagen --stdin
useradd -m -s /bin/bash jjnelson && echo hunter | passwd jjnelson --stdin
useradd -m -s /bin/bash jtfowler && echo 2000 | passwd jtfowler --stdin
useradd -m -s /bin/bash amfleming && echo test | passwd amfleming --stdin
useradd -m -s /bin/bash mslukes && echo batman | passwd mslukes --stdin
useradd -m -s /bin/bash kahalladay && echo trustno1 | passwd kahalladay --stdin
useradd -m -s /bin/bash hjconte && echo thomas | passwd hjconte --stdin
useradd -m -s /bin/bash pmlogan && echo robert | passwd pmlogan --stdin
useradd -m -s /bin/bash agbates && echo love | passwd agbates --stdin
useradd -m -s /bin/bash esswift && echo buster | passwd esswift --stdin
useradd -m -s /bin/bash rsruhlin && echo soccer | passwd rsruhlin --stdin
useradd -m -s /bin/bash ksbricout && echo hockey | passwd ksbricout --stdin
useradd -m -s /bin/bash tbcort && echo killer | passwd tbcort --stdin
useradd -m -s /bin/bash brwake && echo george | passwd brwake --stdin
useradd -m -s /bin/bash kmgreer && echo andrew | passwd kmgreer --stdin
useradd -m -s /bin/bash rasimpson && echo charlie | passwd rasimpson --stdin
useradd -m -s /bin/bash hsstobb && echo superman | passwd hsstobb --stdin
useradd -m -s /bin/bash dblaware && echo dallas | passwd dblaware --stdin
useradd -m -s /bin/bash melee && echo jessica | passwd melee --stdin
useradd -m -s /bin/bash magarverick && echo pepper | passwd magarverick --stdin
useradd -m -s /bin/bash amfortune && echo porsche | passwd amfortune --stdin
useradd -m -s /bin/bash hcbailliet && echo guitar | passwd hcbailliet --stdin
useradd -m -s /bin/bash kpcoakley && echo chelsea | passwd kpcoakley --stdin
useradd -m -s /bin/bash dmbrubaker && echo black | passwd dmbrubaker --stdin
useradd -m -s /bin/bash djverspoor && echo nascar | passwd djverspoor --stdin
useradd -m -s /bin/bash dmdehart && echo jackson | passwd dmdehart --stdin
useradd -m -s /bin/bash crvoltz && echo cameron | passwd crvoltz --stdin
useradd -m -s /bin/bash sswallace && echo 654321 | passwd sswallace --stdin
useradd -m -s /bin/bash jpcrocker && echo computer | passwd jpcrocker --stdin
useradd -m -s /bin/bash cdsims && echo amanda | passwd cdsims --stdin
useradd -m -s /bin/bash elwhitaker && echo wizard | passwd elwhitaker --stdin
useradd -m -s /bin/bash ksmurray && echo xxxxxxxx | passwd ksmurray --stdin
useradd -m -s /bin/bash kgowens && echo mickey | passwd kgowens --stdin
useradd -m -s /bin/bash kdshisler && echo bailey | passwd kdshisler --stdin
useradd -m -s /bin/bash tbreifel && echo knight | passwd tbreifel --stdin
useradd -m -s /bin/bash kkswift && echo purple | passwd kkswift --stdin
useradd -m -s /bin/bash trkabir && echo andrea | passwd trkabir --stdin
useradd -m -s /bin/bash bhcrouse && echo dakota | passwd bhcrouse --stdin
useradd -m -s /bin/bash ekwashington && echo aaaaaa | passwd ekwashington --stdin
useradd -m -s /bin/bash jrsullivan && echo sunshine | passwd jrsullivan --stdin
useradd -m -s /bin/bash tgkapetanovic && echo starwars | passwd tgkapetanovic --stdin
useradd -m -s /bin/bash mgspear && echo boomer | passwd mgspear --stdin
useradd -m -s /bin/bash djfox && echo cowboys | passwd djfox --stdin
useradd -m -s /bin/bash bdconte && echo edward | passwd bdconte --stdin
useradd -m -s /bin/bash dtverspoor && echo charles | passwd dtverspoor --stdin
useradd -m -s /bin/bash asroper && echo booboo | passwd asroper --stdin
useradd -m -s /bin/bash pttyree && echo xxxxxx | passwd pttyree --stdin
useradd -m -s /bin/bash jjtanner && echo bulldog | passwd jjtanner --stdin
useradd -m -s /bin/bash cbhaylock && echo rabbit | passwd cbhaylock --stdin
useradd -m -s /bin/bash skroper && echo peanut | passwd skroper --stdin
useradd -m -s /bin/bash kvanthony && echo john | passwd kvanthony --stdin
useradd -m -s /bin/bash ljblume && echo johnny | passwd ljblume --stdin
useradd -m -s /bin/bash wdkremer && echo spanky | passwd wdkremer --stdin
useradd -m -s /bin/bash rebennett && echo winter | passwd rebennett --stdin
useradd -m -s /bin/bash ekbarbee && echo brandy | passwd ekbarbee --stdin
useradd -m -s /bin/bash emhall && echo tennis | passwd emhall --stdin
useradd -m -s /bin/bash bbcarreira && echo james | passwd bbcarreira --stdin
useradd -m -s /bin/bash ptferguson && echo brandon | passwd ptferguson --stdin
useradd -m -s /bin/bash hjliston && echo firebird | passwd hjliston --stdin
useradd -m -s /bin/bash mbday && echo butter | passwd mbday --stdin
useradd -m -s /bin/bash disteinhour && echo united | passwd disteinhour --stdin
useradd -m -s /bin/bash jcedmonds && echo turtle | passwd jcedmonds --stdin
useradd -m -s /bin/bash sdtakimoto && echo tiffany | passwd sdtakimoto --stdin
useradd -m -s /bin/bash kslarsen && echo zxcvbn | passwd kslarsen --stdin
useradd -m -s /bin/bash dkcates && echo tomcat | passwd dkcates --stdin
useradd -m -s /bin/bash jshaygood && echo golf | passwd jshaygood --stdin
useradd -m -s /bin/bash jcblume && echo bond007 | passwd jcblume --stdin
useradd -m -s /bin/bash ganguyen && echo bear | passwd ganguyen --stdin
useradd -m -s /bin/bash pbminard && echo tiger | passwd pbminard --stdin
useradd -m -s /bin/bash sdharding && echo doctor | passwd sdharding --stdin
useradd -m -s /bin/bash bamcdonald && echo angel | passwd bamcdonald --stdin
useradd -m -s /bin/bash bdkasper && echo junior | passwd bdkasper --stdin
useradd -m -s /bin/bash rbdaly && echo thx1138 | passwd rbdaly --stdin
useradd -m -s /bin/bash njkendrick && echo debbie | passwd njkendrick --stdin
useradd -m -s /bin/bash abwise && echo spider | passwd abwise --stdin
useradd -m -s /bin/bash atober && echo booger | passwd atober --stdin
useradd -m -s /bin/bash rmhunter && echo 1212 | passwd rmhunter --stdin
useradd -m -s /bin/bash ljmartisek && echo fish | passwd ljmartisek --stdin
useradd -m -s /bin/bash cmnazzal && echo matrix | passwd cmnazzal --stdin
useradd -m -s /bin/bash addevincentis && echo teens | passwd addevincentis --stdin
useradd -m -s /bin/bash dwbelforte && echo scooby | passwd dwbelforte --stdin
useradd -m -s /bin/bash cddunn && echo jason | passwd cddunn --stdin
